### PR TITLE
Add three new widgets: button, label and logger

### PR DESCRIPTION
**Pull request by Cycov**
### Button
When pressed it publishes on a topic chosen by the user "True" and when the user releases the button it publishes "False" on the same topic. The message type is `std_msgs/Bool.msg`. 
When pressed, it turns yellow.
Screenshot_20201104_155024_com schneewittchen rosandroid

### Label
Displays white text in a black rectangle. Useful when having multiple joysticks. Does not interact with ROS.
Screenshot_20201104_160248_com schneewittchen rosandroid

### Logger
Displays the message published on a topic chosen by the user in a label. The message type is `std_msgs/String.msg`.

### Additional notes
All three controls can be rotated by 90°, 180° and 270° for landscape use. Below you can see an example using all three new controls and two joysticks.

Screenshot_20201104_154823_com schneewittchen rosandroid

### CODE REVIEW

**Review by NRottmann — CHANGES_REQUESTED** [review]
We recently (today) made somee heavy changes to the general widget structure. Hence, your code has to be reworked before merging. We will have a look into it during the next days. Nevertheless, we highly appreciate your contribution and it looks very good so far. Feel free to contact us also via mail also, if you have any questions.

**Comment by Cycov** [comment]
I won't be able to do the full rework based on your heavy (undocumented) changes the next couple days, or if I should for that matter considering the new version is not as thoroughly tested as the previous version and can't guarantee that the issues will emerge from my side and debugging the entire application is out of scope.

I will take a look in the weekend or the next week. Thank you for your consideration.

P.S. I would propose making a widget creating guide to encourage newcomers in contributing considering that the project is quite versatile and easy to use. If and when I'm done with the rework I can start working on such a document. If you are interested in this proposal [mail me](mailto:hi@cidra.me) hi@cidra.me

**Review by NRottmann — APPROVED** [review]

**Comment by Cycov** [comment]
Regarding this, I did some changes. I could not find how to change the displayed topic on button in Viz configuration. If you could give me some pointers or just make the change directly I would highly appreciate it

**Comment by NRottmann** [comment]
You can change the displayed name of the button in the details section. But I am not sure if it is this what you want to do here.

**Comment by NRottmann** [comment]
Inlcusion of three new widgets designed by [Dragos Circa](https://github.com/Cycov):

-> Button: A simple button widget which, if pressed, returns true and false otherwise
-> Label: A simple label to enhance the structure of the Viz Tab. Does not interact with ROS
-> Logger: A simple std_msgs/String subscriber which displays the subscribed String

**Pull request merged**
