### PR TITLE
Add drag-and-drop placement for widgets

### PR DESCRIPTION
**Pull request by naiveHobo**
Implements positioning and scaling of widgets using gestures as suggested in #51
Adds a *viz options* drawer to enable *edit mode* that gives access to gestured based positioning and scaling. When edit mode is enabled, the widgets won't respond to their normal touch routines and instead only respond to placement and scaling gestures.

### CODE REVIEW

**Comment by Torellin** [comment]
Great contribution, but lets talk about widgets that override touch inputs like the Joystick for example. I've quickly tested your changes and I recognized that the joystick couldn't be moved. Maybe we should introduced a new state in the viz so that user only can drag/drop widgets around without interacting with them.

**Review by Torellin — CHANGES_REQUESTED** [review]
Introducing a "move" state

**Comment by NRottmann** [comment]
Really nice work. I agree with Nico that such a state would make sense. For example, we could include a lock somewhere which signals if the VIZ is in a locked state or can be moved. Also, I would include a rescaling option too.

**Comment by naiveHobo** [comment]
Where would you suggest adding the switch to move state in the UI? Right side of the tool bar only when the user is on the viz tab?
Also, yes just finishing up the scaling functionality as well!

**Comment by NRottmann** [comment]
Would be nice to have the option too slide open a side bar where options can be placed or with a floating action button.

**Comment by naiveHobo** [comment]
move

scale

@NRottmann @Torellin thoughts?

**Comment by Torellin** [comment]
I love it!

**Comment by naiveHobo** [comment]
Should be ready for another review now!

**Comment by NRottmann** [comment]
Nice work. I really like it. If you like just add your name to the contributors in the readme and link your profile/website. Afterwards, I will enable the merge.

**Comment by naiveHobo** [comment]
Done!

**Review by Torellin — APPROVED** [review]
Nice! There are some things that could be changed, but I'll accept the changes for now.
Would be better to check the input event and the "isInEditMode" in the general widgetView class or directly in the WidgetViewGroup, so that for new Widgets this has not to be checked again.

**Pull request merged**
